directory: /data/music            # The default library root directory.
library: /data/music/.beet.blb

import:
    move: true
    resume: yes
    art: true

ui:
    color: yes
plugins: lyrics mbsync fetchart scrub bpd convert badfiles missing embedart

embedart:
    auto: yes                              # Embed album art in the music files

lastgenre:
    canonical: yes
    count: 3
    prefer_specific: yes

chroma:
    auto: yes

lyrics:
    sources: lyricwiki musixmatch genius

mpdupdate:
    host: 127.0.0.1
    port: 6600

convert:
     dest: /data/music
     format: ogg
     copy_album_art: yes
     embed: yes
     never_convert_lossy_files: true
